#pragma config(Motor,  port1,           TowerIntake,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BRD,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FRD,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FLD,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           BLD,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Flywheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Puncher,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          SideIntake,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Platform
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

//Libraries
#include "Vex_Competition_Includes.c"

//Pre-Autonomous//
void pre_auton()
{
}


// Autonomous Mode //
task autonomous()
{
	// in case we were running
	stopTask( usercontrol );
}


//User Control//
task usercontrol()
{
	//Create "deadzone" variables. AdjuFlywheel threshold value to increase/decrease deadzone
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;

	while (true)
	{
		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;

		//Remote Control Commands
		motor[FRD] = Y1 - X2 - X1;
		motor[BRD] =  Y1 - X2 + X1;
		motor[FLD] = Y1 + X2 + X1;
		motor[BLD] =  Y1 + X2 - X1;


		//Lift
		motor[Lift]  = vexRT[Ch2Xmtr2];

		//Tower Intake Up
		if(vexRT[Btn5DXmtr2] == 1)
		{
			motor[TowerIntake] = 127;
		}

		//Bottom Intake In
		else if(vexRT[Btn5UXmtr2] == 1)
		{
			motor[SideIntake] = 127;
		}

		//Top & Bottom Intake Out
		else if(vexRT[Btn6DXmtr2] == 1)
		{
			motor[TowerIntake] = -127;
			motor[SideIntake] = -127;
		}

		//Top & Bottom Intake In
		else if(vexRT[Btn6UXmtr2] == 1)
		{
			motor[TowerIntake] = 127;
			motor[SideIntake] = 127;
		}

		//Top & Bottom Intake In
		else if(vexRT[Btn8DXmtr2] == 1)
		{
			motor[TowerIntake] = -127;
		}

		else
		{
			motor[TowerIntake] = 0;
			motor[SideIntake] = 0;
		}


		//Flywheel
		if(vexRT[Btn6U] == 1)
		{
			motor[Flywheel] = 70;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[Flywheel] = 70;
		}
		else
		{
			motor[Flywheel] = 0
		}
	}
}
